version: 1.0.{build}
image: Visual Studio 2022

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

before_build:
  - dotnet restore

build_script:
  - dotnet build --configuration Release

test_script:
  - dotnet test --configuration Release --no-build --no-restore ../HelloWorld.Tests/HelloWorld.Tests.csproj

after_test:
  - ps: dotnet tool install -g Cake.Tool
  - ps: dotnet cake build.cake -target=Documentation